services:
  db:
    build:
      context: ./citizen-dashboard-backend/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./citizen-dashboard-backend/backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SEARCH_API_PORT=${SEARCH_API_PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SEARCH_API_PORT}:5000"
    command: ["sh", "-c", "python populate_db.py && python search_api.py"]

  frontend:
    build:
      context: ./citizen-dashboard-frontend
      dockerfile: Dockerfile
    environment:
      - VITE_SEARCH_API_PORT=${SEARCH_API_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend

volumes:
  db_data: