apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: citizen-dashboard
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - name: pgadmin-port
    port: 15432
    targetPort: 80
    nodePort: 30080