apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: citizen-dashboard
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:7.8
        imagePullPolicy: Always
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@cd.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        ports:
        - containerPort: 80
