# .github/workflows/docker-publish.yml

name: Build, Scan, and Publish Docker Images

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write         # Allows read and write access to repository contents
  pull-requests: write    # Allows creating and modifying pull requests

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [data_fetcher, data_store]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for accurate commit SHA

      - name: List Repository Contents (Debugging)
        run: |
          echo "Listing repository root:"
          ls -la
          echo "Listing services directory:"
          ls -la services
          echo "Listing data_store directory:"
          ls -la services/data_store
          echo "Listing data_fetcher directory:"
          ls -la services/data_fetcher

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Set Image Tags
        id: set_tags
        run: |
          # Convert repository owner to lowercase
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          COMPONENT=${{ matrix.component }}
          SHA=${{ github.sha }}
          REF=${{ github.ref }}

          # Determine if the event is a push to main/master
          if [[ "${{ github.event_name }}" == "push" && ( "${REF}" == "refs/heads/main" || "${REF}" == "refs/heads/master" ) ]]; then
            TAGS="ghcr.io/${OWNER}/${COMPONENT}:latest ghcr.io/${OWNER}/${COMPONENT}:${SHA}"
          else
            TAGS="ghcr.io/${OWNER}/${COMPONENT}:${SHA}"
          fi

          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: services/${{ matrix.component }}
          push: false
          tags: ${{ env.TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ env.OWNER }}/${{ matrix.component }}:latest
          format: 'table'
          exit-code: 1
          ignore-unfixed: true

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: services/${{ matrix.component }}
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify Image Push
        run: |
          echo "Successfully pushed images for ${{ matrix.component }} with tags: $TAGS"
