# .github/workflows/docker-publish.yml

name: Build, Scan, and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write         # Allows read and write access to repository contents
  pull-requests: write    # Allows creating and modifying pull requests

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [data-fetcher, data-store]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Cache Docker layers
        uses: actions/cache@v4.1.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Set Image Tags
        id: set_tags
        run: |
          # Convert repository owner and name to lowercase
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          COMPONENT=${{ matrix.component }}
          SHA=${{ github.sha }}

          # Export OWNER and REPO to the environment for later use
          echo "OWNER=${OWNER}" >> $GITHUB_ENV
          echo "REPO=${REPO}" >> $GITHUB_ENV

          # Conditional tagging based on the event and branch
          if [[ "${{ github.event_name }}" == "push" && ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master") ]]; then
            echo "TAGS=ghcr.io/${OWNER}/${COMPONENT}:latest ghcr.io/${OWNER}/${COMPONENT}:${SHA}" >> $GITHUB_ENV
          else
            echo "TAGS=ghcr.io/${OWNER}/${COMPONENT}:${SHA}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: services/${{ matrix.component }}
          push: false
          load: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ matrix.component }}:latest
            ghcr.io/${{ env.OWNER }}/${{ matrix.component }}:${{ github.sha }}
          # Enable build cache to speed up builds
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # - name: Scan Docker Image with Trivy
      #   uses: aquasecurity/trivy-action@0.28.0
      #   with:
      #     image-ref: ghcr.io/${{ env.OWNER }}/${{ matrix.component }}:latest
      #     format: 'table'
      #     exit-code: 1
      #     ignore-unfixed: true

      - name: Push Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: services/${{ matrix.component }}
          push: true
          tags: ${{ env.TAGS }}
          # Enable build cache to speed up builds
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify Image Push
        run: |
          echo "Successfully pushed images for ${matrix.component} with tags: $TAGS"
