
name: Citizen Dashboard Deployment
on:
  push:
    branches:
    - main

jobs:
  build-and-deploy-cd:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER": ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD": ${{ secrets.POSTGRES_PASSWORD }}
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2 

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: |
            build-script:
              - '.github/**'
            data-fetcher:
              - 'services/data-fetcher/**'
            data-store:
              - 'services/data-store/**'  
            postgres:
              - 'services/postgres/**'
            kafka:
              - 'services/kafka/**'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy service to K8S (postgres)
        if: steps.changes.outputs.postgres == 'true' || steps.changes.outputs.build-script == 'true'
        run: |
          python services/postgres/deployment/deploy.py
    
      - name: Deploy service to K8S (kafka)
        if: steps.changes.outputs.kafka == 'true' || steps.changes.outputs.build-script == 'true'
        run: |
          python services/kafka/deployment/deploy.py

      - name: Deploy data-fetcher
        if: steps.changes.outputs.data-fetcher == 'true' || steps.changes.outputs.build-script == 'true'
        run: |
          python services/data-fetcher/deployment/deploy.py -t dev-${{ github.actor }}-${{ github.ref_name }}      
  
      - name: Deploy service to K8S (data-store)
        if: steps.changes.outputs.data-store == 'true' || steps.changes.outputs.build-script == 'true'
        run: |
          python services/data-store/deployment/deploy.py -t dev-${{ github.actor }}-${{ github.ref_name }}
