
name: Citizen Dashboard main Github Actions
on:
  push:
    branches:
    - deployment
  pull_request:
    branches:
    - deployment

jobs:
  build-application:
    name: Build application and push image to dockerhub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2 

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            data-fetcher:
              - 'citizen-dashboard-backend/data-fetcher/**'  
            backend:
              - 'citizen-dashboard-backend/backend/**'
            db:
              - 'citizen-dashboard-backend/db/**'
            scripts:
              - 'citizen-dashboard-backend/scripts/**'
            infra:
              - 'citizen-dashboard-infra/**'
            kafka:
              - 'citizen-dashboard-infra/kafka/**'

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

## DATA FETCHER -----------------------------
      - name: Build and push Docker image (data-fetcher)
        if: steps.changes.outputs.data-fetcher == 'true'
        id: push
        uses: docker/build-push-action@v3
        with:
            context: citizen-dashboard-backend/data-fetcher/.
            file: citizen-dashboard-backend/data-fetcher/Dockerfile
            push: true
            tags: |
              korabel/cd-data-fetcher:latest
              korabel/cd-data-fetcher:${{ github.sha }}
      
      - name: Deploy service to K8S (data-fetcher)
        if: steps.changes.outputs.data-fetcher == 'true'
        run: |
          kubectl apply -f citizen-dashboard-backend/data-fetcher/deployment/deployment.yaml
          kubectl apply -f citizen-dashboard-backend/data-fetcher/deployment/service.yaml
          kubectl rollout restart deployment data-fetcher -n default

## INFRA -----------------------------
      - name: Configure Infra namespace in K8S
        if: steps.changes.outputs.infra == 'true'
        run: |
          kubectl apply -f citizen-dashboard-infra/namespace.yaml

## KAFKA -----------------------------
      - name: Deploy service to K8S (kafka)
        if: steps.changes.outputs.kafka == 'true'
        run: |
          kubectl apply -f citizen-dashboard-infra/kafka/zookeeper.yaml
          kubectl apply -f citizen-dashboard-infra/kafka/kafka.yaml

