apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fetcher
  namespace: citizen-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-fetcher
  template:
    metadata:
      labels:
        app: data-fetcher
    spec:
      containers:
      - name: data-fetcher
        image: _IMAGENAME_
        ports:
        - containerPort: 80