apiVersion: v1
kind: Service
metadata:
  name: data-fetcher
  namespace: citizen-dashboard
spec:
  selector:
    app: data-fetcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer